name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh

    # Get a short-lived NuGet API key
    - name: NuGet login
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: ${{ secrets.NUGET_USER }}

    # Push the package
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
      run: ./Push.ps1
      shell: pwsh

    - name: Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: artifacts
        path: artifacts/**/*
